management:
    servlet-path: /api
    security:
        enabled: false
spring:
    application:
        name: service-file
    profiles:
        active: @profileActive@
    jackson:
        serialization.write_dates_as_timestamps: false
    mvc:
        favicon:
            enabled: false
    #支持云配置
#    cloud:
#        config:
#          uri: http://localhost:8060

server:
    port: 9002
    session:
        cookie:
            http-only: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
info:
  name: 文件服务
  desc: 文件常用的操作都在这里，直接调用